FROM azukiapp/ruby:2.2
MAINTAINER Azuki <support@azukiapp.com>

ADD install-qt-webkit.sh /install-qt-webkit.sh
ADD install-phantomjs.sh /install-phantomjs.sh

CMD ["/install-qt-webkit.sh"]
CMD ["/install-phantomjs.sh"]
